paths:
  raw_data: data/raw/ValeursFoncieres-2025.txt
  clean_data: data/clean/dvf_clean.parquet
  processed_data: data/processed/dvf_core.parquet
  appartenance_communes: data/clean/appartenance_communes.parquet
  stats_communes: data/clean/stats_communes.parquet
  stats_chomage: data/clean/stats_chomage.parquet
  stats_intercommunes: data/clean/stats_intercommunes_2023.parquet